apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: CA
    server: https://89.169.168.255
  name: NAME
contexts:
- context:
    cluster: NAME
    namespace: NAMESPACE
    user: NAME
  name: NAME
current-context: NAME
kind: Config
preferences: {}
users:
- name: NAME
  user:
    token: TOKEN
